<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>docs/README.md</PackageReadmeFile>
        <Description>Software development kit for the ProjectManager.com API for DotNet</Description>
        <PackageTags>projectmanager project management task tracking projects tasks</PackageTags>
        <Copyright>Copyright 2023 - 2026</Copyright>
        <PackageReleaseNotes>
## Patch notes for 2026.160.203

These patch notes summarize the changes from version 2026.156.162.

Added 5 new endpoints:
* Project.CreateProjectExport
* Resource.BulkUpdateResources
* ResourceTeam.GetResourceTeam
* TaskStatus.MoveTasksToATaskStatus
* WorkSpace.UpdateCurrentWorkspaceSettings

Renamed 10 endpoints:
* Renamed Meetings.CreateWeeklyRecurringMeetings to MeetingRecurrency.CreateWeeklyRecurringMeetings
* Renamed Meetings.CreateMonthlyRecurringMeetings to MeetingRecurrency.CreateMonthlyRecurringMeetings
* Renamed Meetings.CreateDailyRecurringMeetings to MeetingRecurrency.CreateDailyRecurringMeetings
* Renamed Meetings.CreateYearlyRecurringMeetings to MeetingRecurrency.CreateYearlyRecurringMeetings
* Renamed Meetings.DeleteRecurringMeetings to MeetingRecurrency.DeleteRecurringMeetings
* Renamed Meetings.ValidateRecurringMeetingSettings to MeetingRecurrency.ValidateRecurringMeetingSettings
* Renamed Meetings.UpdateRecurringMeetingSettings to MeetingRecurrency.UpdateRecurringMeetingSettings
* Renamed ProjectMembers.UpdateUserProjectMembership to ProjectMembers.CreateOrUpdateUserProjectMembership
* Renamed ResourceTeam.RetrieveResourceTeams to ResourceTeam.QueryResourceTeams
* Renamed WorkSpace.RetrieveWorkspaces to WorkSpace.RetrieveCurrentWorkspace

Changes to data models:
* IntegrationProviderDto: Added new field `unauthorized`
* RecurringTaskChangeSetDetails: Added new field `recurrences`
* ResourceDto: Added new field `roleId`
* TaskDetailsDto: Added new field `baseline`
* UserRolePermissionsDto: Added new field `useMcp`
* WorkSpaceDto: Added new field `accountOwnerId`
* WorkSpaceDto: Added new field `status`
* WorkSpaceDto: Added new field `isActive`
* WorkSpaceDto: Added new field `isReseller`
* WorkSpaceDto: Added new field `licenses`
* WorkSpaceDto: Added new field `settings`
* WorkSpacePermissionsDto: Added new field `changeOwnEmail`
* WorkSpacePermissionsDto: Added new field `useMcp`
* WorkSpaceUserInfoDto: Added new field `isSocial`

Deprecated 5 old endpoints:
* Holiday.QueryResourceHolidays
* Holiday.QueryCountryHolidays
* Holiday.QueryGlobalHolidays
* ProjectMembers.UpdateAListOfUserProjectMembership
* ProjectMembers.CreateUserProjectMembership


        </PackageReleaseNotes>
        <PackageIcon>docs/logo.png</PackageIcon>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
		<version>2026.160.203</version>
        <Authors>ProjectManager.com</Authors>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Text.Json" Version="9.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <None
                Include="../README.md"
                PackagePath="/docs"
                Pack="true" />
        <None
                Include="../LICENSE"
                PackagePath="/docs"
                Pack="true" />
        <None
                Include="../images/logo.png"
                PackagePath="/docs"
                Pack="true" />
    </ItemGroup>

</Project>
