<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>docs/README.md</PackageReadmeFile>
        <Description>Software development kit for the ProjectManager.com API for DotNet</Description>
        <PackageTags>projectmanager project management task tracking projects tasks</PackageTags>
        <Copyright>Copyright 2023 - 2026</Copyright>
        <PackageReleaseNotes>
## Patch notes for 2026.157.126

These patch notes summarize the changes from version 2026.156.162.

Added 2 new endpoints:
* Integration.UpdateIntegrationMetadata
* WorkSpace.UpdateSettingsForTheCurrentWorkspace

Renamed 1 endpoints:
* Renamed WorkSpace.RetrieveWorkspaces to WorkSpace.RetrieveTheCurrentWorkspace

Changes to existing endpoints:
* Breaking change: TaskField.RetrieveTaskFieldValue path changed from `/api/data/tasks/{taskId}/fields/{fieldId}` to `/api/data/tasks/{taskId}/fields/{fieldId}/values`
* Breaking change: TaskField.UpdateTaskFieldValue path changed from `/api/data/tasks/{taskId}/fields/{fieldId}` to `/api/data/tasks/{taskId}/fields/{fieldId}/values`
* Breaking change: TaskStatus.UpdateTaskStatus path changed from `/api/data/tasks/statuses/{taskStatusId}` to `/api/data/projects/{projectId}/tasks/statuses`
* TaskStatus.UpdateTaskStatus added path parameter `projectId`
* TaskStatus.UpdateTaskStatus removed path parameter `taskStatusId`
* Breaking change: TaskStatus.DeleteTaskStatus path changed from `/api/data/projects/{projectId}/tasks/statuses/{taskStatusId}` to `/api/data/tasks/statuses/{taskStatusId}`
* TaskStatus.DeleteTaskStatus removed path parameter `projectId`

Changes to data models:
* IntegrationDto: Added new field `metadata`
* IntegrationProviderDto: Added new field `unauthorized`
* TaskDetailsDto: Added new field `baseline`
* WorkSpaceDto: Added new field `settings`


        </PackageReleaseNotes>
        <PackageIcon>docs/logo.png</PackageIcon>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
		<version>2026.157.126</version>
        <Authors>ProjectManager.com</Authors>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Text.Json" Version="9.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <None
                Include="../README.md"
                PackagePath="/docs"
                Pack="true" />
        <None
                Include="../LICENSE"
                PackagePath="/docs"
                Pack="true" />
        <None
                Include="../images/logo.png"
                PackagePath="/docs"
                Pack="true" />
    </ItemGroup>

</Project>
